-- PostgreSQL schema generated by Alembic migration 0001_initial (pg_dump --schema-only).
-- Source of truth: backend/alembic/versions/. Apply with: alembic upgrade head
-- Name: ai_runs; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.ai_runs (
    id character varying(32) NOT NULL,
    dataset_id character varying(32) NOT NULL,
    kind character varying(16) NOT NULL,
    mode character varying(16) NOT NULL,
    model character varying(128),
    prompt_version character varying(32) NOT NULL,
    input_chars integer NOT NULL,
    input_tokens integer,
    output_tokens integer,
    llm_calls integer NOT NULL,
    latency_ms integer NOT NULL,
    cost_usd double precision,
    question text,
    output jsonb,
    error text,
    created_at timestamp with time zone NOT NULL
);
-- Name: analysis_results; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.analysis_results (
    id integer NOT NULL,
    dataset_id character varying(32) NOT NULL,
    config_hash character varying(64) NOT NULL,
    engine_version character varying(32) NOT NULL,
    result jsonb NOT NULL,
    processing_ms integer NOT NULL,
    created_at timestamp with time zone NOT NULL
);
-- Name: analysis_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
CREATE SEQUENCE public.analysis_results_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
-- Name: analysis_results_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
ALTER SEQUENCE public.analysis_results_id_seq OWNED BY public.analysis_results.id;
-- Name: datasets; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.datasets (
    id character varying(32) NOT NULL,
    name character varying(255) NOT NULL,
    stored_path character varying(512) NOT NULL,
    file_size_bytes integer NOT NULL,
    status character varying(32) NOT NULL,
    error text,
    validation_report jsonb,
    column_mapping jsonb,
    created_at timestamp with time zone NOT NULL
);
-- Name: events; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.events (
    id integer NOT NULL,
    dataset_id character varying(32) NOT NULL,
    source_row integer NOT NULL,
    case_id character varying(255) NOT NULL,
    original_activity character varying(255) NOT NULL,
    activity character varying(255) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    start_timestamp timestamp with time zone,
    resource character varying(255),
    department character varying(255),
    status character varying(255),
    amount double precision,
    customer_id character varying(255),
    location character varying(255),
    priority character varying(255),
    extra jsonb
);
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
CREATE SEQUENCE public.events_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
-- Name: events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
ALTER SEQUENCE public.events_id_seq OWNED BY public.events.id;
-- Name: invalid_rows; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.invalid_rows (
    id integer NOT NULL,
    dataset_id character varying(32) NOT NULL,
    source_row integer NOT NULL,
    issue character varying(64) NOT NULL,
    detail text NOT NULL,
    raw jsonb
);
-- Name: invalid_rows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
CREATE SEQUENCE public.invalid_rows_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
-- Name: invalid_rows_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
ALTER SEQUENCE public.invalid_rows_id_seq OWNED BY public.invalid_rows.id;
-- Name: analysis_results id; Type: DEFAULT; Schema: public; Owner: -
ALTER TABLE ONLY public.analysis_results ALTER COLUMN id SET DEFAULT nextval('public.analysis_results_id_seq'::regclass);
-- Name: events id; Type: DEFAULT; Schema: public; Owner: -
ALTER TABLE ONLY public.events ALTER COLUMN id SET DEFAULT nextval('public.events_id_seq'::regclass);
-- Name: invalid_rows id; Type: DEFAULT; Schema: public; Owner: -
ALTER TABLE ONLY public.invalid_rows ALTER COLUMN id SET DEFAULT nextval('public.invalid_rows_id_seq'::regclass);
-- Name: ai_runs ai_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.ai_runs
    ADD CONSTRAINT ai_runs_pkey PRIMARY KEY (id);
-- Name: analysis_results analysis_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.analysis_results
    ADD CONSTRAINT analysis_results_pkey PRIMARY KEY (id);
-- Name: datasets datasets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.datasets
    ADD CONSTRAINT datasets_pkey PRIMARY KEY (id);
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);
-- Name: invalid_rows invalid_rows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.invalid_rows
    ADD CONSTRAINT invalid_rows_pkey PRIMARY KEY (id);
-- Name: ix_ai_runs_dataset; Type: INDEX; Schema: public; Owner: -
CREATE INDEX ix_ai_runs_dataset ON public.ai_runs USING btree (dataset_id, created_at);
-- Name: ix_analysis_dataset_cfg; Type: INDEX; Schema: public; Owner: -
CREATE INDEX ix_analysis_dataset_cfg ON public.analysis_results USING btree (dataset_id, config_hash);
-- Name: ix_events_dataset_activity; Type: INDEX; Schema: public; Owner: -
CREATE INDEX ix_events_dataset_activity ON public.events USING btree (dataset_id, activity);
-- Name: ix_events_dataset_case_ts; Type: INDEX; Schema: public; Owner: -
CREATE INDEX ix_events_dataset_case_ts ON public.events USING btree (dataset_id, case_id, "timestamp");
-- Name: ix_invalid_rows_dataset; Type: INDEX; Schema: public; Owner: -
CREATE INDEX ix_invalid_rows_dataset ON public.invalid_rows USING btree (dataset_id);
-- Name: ai_runs ai_runs_dataset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.ai_runs
    ADD CONSTRAINT ai_runs_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES public.datasets(id) ON DELETE CASCADE;
-- Name: analysis_results analysis_results_dataset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.analysis_results
    ADD CONSTRAINT analysis_results_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES public.datasets(id) ON DELETE CASCADE;
-- Name: events events_dataset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES public.datasets(id) ON DELETE CASCADE;
-- Name: invalid_rows invalid_rows_dataset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.invalid_rows
    ADD CONSTRAINT invalid_rows_dataset_id_fkey FOREIGN KEY (dataset_id) REFERENCES public.datasets(id) ON DELETE CASCADE;
-- PostgreSQL database dump complete
